FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS="http://+:8080"

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["/AuthService.API/AuthService.API.csproj", "AuthService.API/"]
COPY ["/AuthService.Persistence/AuthService.Persistence.csproj", "AuthService.Persistence/"]
COPY ["/AuthService.Domain/AuthService.Domain.csproj", "AuthService.Domain/"]
COPY ["/AuthService.Application/AuthService.Application.csproj", "AuthService.Application/"]
RUN dotnet restore "AuthService.API/AuthService.API.csproj"

COPY /AuthService.API/. AuthService.API/
COPY /AuthService.Application/. AuthService.Application/
COPY /AuthService.Domain/. AuthService.Domain/
COPY /AuthService.Persistence/. AuthService.Persistence/

WORKDIR "/src/AuthService.API"
RUN dotnet build "AuthService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "AuthService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AuthService.API.dll"]
