FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8081
ENV ASPNETCORE_URLS="http://+:8081"

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["TaskService.API/TaskService.API.csproj", "TaskService.API/"]
COPY ["TaskService.Persistence/TaskService.Persistence.csproj", "TaskService.Persistence/"]
COPY ["TaskService.Domain/TaskService.Domain.csproj", "TaskService.Domain/"]
COPY ["TaskService.Application/TaskService.Application.csproj", "TaskService.Application/"]
RUN dotnet restore "TaskService.API/TaskService.API.csproj"

COPY TaskService.API/. TaskService.API/
COPY TaskService.Application/. TaskService.Application/
COPY TaskService.Domain/. TaskService.Domain/
COPY TaskService.Persistence/. TaskService.Persistence/

WORKDIR "/src/TaskService.API"
RUN dotnet build "TaskService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "TaskService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskService.API.dll"]
